import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function copyToClipboard(text: string): boolean {
  let successful = false;
  
  // Apply fallback first synchronously. This MUST run in the exact same call stack 
  // as the click event gesture to work in restrictive iframes.
  try {
    const textArea = document.createElement("textarea");
    textArea.value = text;
    
    // Prevent scrolling to the bottom of the page
    textArea.style.top = "0";
    textArea.style.left = "0";
    textArea.style.position = "fixed";
    textArea.style.opacity = "0";

    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();

    successful = document.execCommand('copy');
    document.body.removeChild(textArea);
  } catch (err) {
    console.error('Fallback clipboard copy failed', err);
  }

  if (successful) {
    return true;
  }

  // Modern API as a secondary attempt (will run async but we return true immediately if fallback failed)
  if (navigator?.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(text).catch(err => {
      console.warn("Clipboard API failed", err);
    });
    return true; // Assume it will succeed or user will get a prompt
  }
  
  return false;
}

export function generateBashCommand(directory: string, prefix: string, action: 'rename' | 'delete' = 'rename', dryRun: boolean = false): string {
  const safeDir = directory.replace(/'/g, "'\\''");
  const safePrefix = prefix.replace(/'/g, "'\\''");
  
  const cmd = action === 'delete' ? 'rm' : 'mv -n';
  const prefixHandling = action === 'delete' ? '' : `
  # Remove the prefix from the beginning of the filename
  newbase="\${base#"$PREFIX"}"`;

  const condition = action === 'delete' 
    ? `    if [ "$DRY_RUN" = true ]; then
      echo "[DRY RUN] Would delete: $file"
    else
      echo "Deleting: $file"
      rm "$file"
    fi`
    : `  # Rename the file if the new name is different
  if [ "$base" != "$newbase" ]; then
    if [ "$DRY_RUN" = true ]; then
      echo "[DRY RUN] Would rename: $base -> $newbase"
    else
      echo "Renaming: $base -> $newbase"
      mv -n "$file" "$dir/$newbase"
    fi
  fi`;

  return `#!/usr/bin/env bash
# Auto-generated by Prefix Remover
# safely batch ${action} files by matching a prefix

TARGET_DIR='${safeDir}'
PREFIX='${safePrefix}'
DRY_RUN=${dryRun ? 'true' : 'false'}

echo "Searching in: $TARGET_DIR"
echo "${action === 'delete' ? 'Deleting files with' : 'Removing'} prefix: '$PREFIX'"
if [ "$DRY_RUN" = true ]; then
  echo ">>> DRY RUN MODE ESTABLISHED. NO FILES WILL BE MODIFIED. <<<"
fi
echo "----------------------------------------"

find "$TARGET_DIR" -type f -name "$PREFIX*" -print0 | while IFS= read -r -d '' file; do
  dir=$(dirname "$file")
  base=$(basename "$file")
  ${prefixHandling}
  
${condition}
done

echo "Done!"
`;
}

export function generatePowerShellCommand(directory: string, prefix: string, action: 'rename' | 'delete' = 'rename', dryRun: boolean = false): string {
  const safeDir = directory.replace(/'/g, "''");
  const safePrefix = prefix.replace(/'/g, "''");

  const actionBlock = action === 'delete' ? `
    if ($DryRun) {
        Write-Host "[DRY RUN] Would delete: $($_.Name)" -ForegroundColor Yellow
    } else {
        Write-Host "Deleting: $($_.Name)"
        Remove-Item -Path $_.FullName -Force
    }` : `
    $newName = $_.Name.Substring($Prefix.Length)
    if ($DryRun) {
        Write-Host "[DRY RUN] Would rename: $($_.Name) -> $newName" -ForegroundColor Yellow
    } else {
        Write-Host "Renaming: $($_.Name) -> $newName"
        Rename-Item -Path $_.FullName -NewName $newName -PassThru
    }`;

  return `<#
.SYNOPSIS
Auto-generated by Prefix Remover to safely batch ${action} files.
#>

$TargetDir = '${safeDir}'
$Prefix = '${safePrefix}'
$DryRun = ${dryRun ? '$true' : '$false'}

Write-Host "Searching in: $TargetDir"
Write-Host "${action === 'delete' ? 'Deleting files with' : 'Removing'} prefix: '$Prefix'"
if ($DryRun) {
    Write-Host ">>> DRY RUN MODE ESTABLISHED. NO FILES WILL BE MODIFIED. <<<" -ForegroundColor Yellow
}
Write-Host "----------------------------------------"

Get-ChildItem -Path $TargetDir -Filter "$Prefix*" -File -Recurse | ForEach-Object {${actionBlock}
}

Write-Host "Done!"
`;
}
